services:
  llama-server:
    image: ${LLAMA_GPU_IMAGE}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
